name: C Program CI

on:
  push:
    path:
      - '**.c'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Cファイルをコンパイル
        run: gcc -o HelloWorld HelloWorld.c

      - name: 実行して出力を確認
        run: ./HelloWorld
